# Generated by Django 5.0.6 on 2024-12-26 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0003_commentfile_commentimage_postimage_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name_plural": "Categories"},
        ),
        migrations.RemoveField(
            model_name="comment",
            name="updated_at",
        ),
        migrations.RemoveField(
            model_name="postfile",
            name="post",
        ),
        migrations.AddField(
            model_name="comment",
            name="files",
            field=models.ManyToManyField(blank=True, to="forum.commentfile"),
        ),
        migrations.AddField(
            model_name="comment",
            name="images",
            field=models.ManyToManyField(blank=True, to="forum.commentimage"),
        ),
        migrations.AddField(
            model_name="post",
            name="files",
            field=models.ManyToManyField(blank=True, to="forum.postfile"),
        ),
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ManyToManyField(blank=True, to="forum.postimage"),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to="forum.category",
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="views",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="postfile",
            name="file",
            field=models.FileField(upload_to="forum/post_files/"),
        ),
        migrations.AlterField(
            model_name="postfile",
            name="file_size",
            field=models.IntegerField(),
        ),
    ]
