# Generated by Django 5.0.6 on 2024-12-26 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0004_alter_category_options_remove_comment_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="files",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="images",
        ),
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.RemoveField(
            model_name="post",
            name="files",
        ),
        migrations.RemoveField(
            model_name="post",
            name="images",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="join_date",
        ),
        migrations.AddField(
            model_name="postfile",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_files",
                to="forum.post",
            ),
        ),
        migrations.AddField(
            model_name="postimage",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_images",
                to="forum.post",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="forum.category"
            ),
        ),
        migrations.DeleteModel(
            name="CommentFile",
        ),
        migrations.DeleteModel(
            name="CommentImage",
        ),
    ]
